version: '3.9'

services:
  db:
    image: mysql:8-debian
    container_name: db
    restart: unless-stopped
    environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=paytabs
        - MYSQL_USER=paytabs
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  php:
    image: hatemsoliman13/paytabs:1.0
    container_name: app
    build: .
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/paytabs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: